name: dev-ios.yml

on:
  pull_request:
    branches: [ dev ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Unit tests
      run: xcodebuild test -scheme cro_ios -project cro_ios.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}

