name: ci-prod.yml

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: test iOS (${{ matrix.ios }})
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
          - xcode: "13.1"
            ios: "15.0"
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme BudgetOnTheGo -project BudgetOnTheGo.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=$' | xcpretty && exit ${PIPESTATUS[0]}
